#!/bin/bash

# The following symbols (past the first nine) are taken from vivante.h.

FUNCS=$(nm -D --format=bsd --defined-only ${1-.libs/libdrm_vivante.so} | awk '{print $3}'| while read func; do
( grep -q "^$func$" || echo $func )  <<EOF
__bss_end__
__bss_start__
__bss_start
__end__
_bss_end__
_edata
_end
_fini
_init
drm_vivante_bo_create
drm_vivante_bo_destroy
drm_vivante_bo_lock
drm_vivante_bo_unlock
drm_vivante_bo_cache
drm_vivante_bo_getinfo
EOF
done)
